import "server-only";
import { desc, eq, isNull, and } from "drizzle-orm";
import { db, schema } from "@/db";
import type { DeadlineStatus } from "@/db/schema";
import { ALL_JURISDICTIONS } from "@/lib/compliance/rules";

export type DeadlineRow = {
  id: string;
  name: string;
  jurisdiction: string;
  form: string | null;
  taxPeriod: string | null;
  dueDate: number; // epoch ms
  extendedDueDate: number | null;
  status: DeadlineStatus;
  workItemId: string | null;
  ruleKey: string | null;
  autoGenerated: boolean;
  organizationId: string | null;
  orgName: string | null;
};

export type DeadlinesData = {
  deadlines: DeadlineRow[];
  jurisdictions: string[];
  clients: { id: string; name: string }[];
};

export async function loadDeadlines(): Promise<DeadlinesData> {
  const rows = await db
    .select({
      id: schema.complianceDeadlines.id,
      name: schema.complianceDeadlines.name,
      jurisdiction: schema.complianceDeadlines.jurisdiction,
      form: schema.complianceDeadlines.form,
      taxPeriod: schema.complianceDeadlines.taxPeriod,
      dueDate: schema.complianceDeadlines.dueDate,
      extendedDueDate: schema.complianceDeadlines.extendedDueDate,
      status: schema.complianceDeadlines.status,
      workItemId: schema.complianceDeadlines.workItemId,
      ruleKey: schema.complianceDeadlines.ruleKey,
      autoGenerated: schema.complianceDeadlines.autoGenerated,
      organizationId: schema.complianceDeadlines.organizationId,
      orgName: schema.organizations.name,
    })
    .from(schema.complianceDeadlines)
    .leftJoin(
      schema.organizations,
      eq(schema.complianceDeadlines.organizationId, schema.organizations.id),
    )
    .orderBy(desc(schema.complianceDeadlines.dueDate));

  const clients = await db
    .select({ id: schema.organizations.id, name: schema.organizations.name })
    .from(schema.organizations)
    .where(and(eq(schema.organizations.isClient, true), isNull(schema.organizations.deletedAt)))
    .orderBy(schema.organizations.name);

  const deadlines: DeadlineRow[] = rows.map((r) => ({
    ...r,
    dueDate: r.dueDate.getTime(),
    extendedDueDate: r.extendedDueDate ? r.extendedDueDate.getTime() : null,
  }));

  // Jurisdictions present in data plus the bundled set, deduped.
  const present = new Set(deadlines.map((d) => d.jurisdiction));
  const jurisdictions = Array.from(new Set([...ALL_JURISDICTIONS, ...present]));

  return { deadlines, jurisdictions, clients };
}
